[package]
name = "rookpi"
version = "0.1.0"
edition = "2024"

[lib]
name = "rookpi_lib"

[dependencies]
tauri = { version = "2.5.1", features = [] }

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }
